# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App
  pod 'SnapKit', '~> 5.0.0'
  pod 'Skin', :path => '../Skin'
  pod 'SwiftyJSON', :path => '../SwiftyJSON'
  # pod 'SwiftReflection', :path =>'../SwiftReflection'

end
